config/routes.rb
Rails.application.routes.draw do

  root to: "home#show"

  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: "sessions#create"
  get '/dashboard', to: 'users#show'
  delete "/logout", to: "sessions#destroy", as: :logout

end

app/models/commit.rb
class Commit
  attr_reader :author, :message, :repo, :created_at

  def initialize(commit)
    @author     = commit["commit"]["author"]["name"]
    @message    = commit["commit"]["message"]
    @repo       = commit["commit"]["url"].split("/")[5]
    @created_at = commit["commit"]["author"]["date"]
  end

end

app/models/follower.rb
class Follower
  def initialize(follow)
    @name = follow["login"]
    @url  = follow["html_url"]
  end
end

app/models/following.rb
class Following
  def initialize(follow)
    @name = follow["login"]
    @url = follow["html_url"]
  end
end

app/models/organization.rb
class Organization
  attr_reader :name, :url

  def initialize(org)
    @name = org["login"]
    @url = org["url"].sub("api.", "")
  end

end

app/models/repository.rb
class Repository
  attr_reader :name, :owner, :url, :description

  def initialize(repository)
    @name        = repository["name"]
    @owner       = repository["owner"]["login"]
    @url         = repository["url"].sub("api.", "")
    @description = repository["description"]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.nickname           = auth_info.extra.raw_info.login
      new_user.token              = auth_info.credentials.token
      new_user.avatar_url         = auth_info.extra.raw_info.avatar_url
    end
  end

  def stars
    stars = UserService.new(self).stars
  end

  def following
    following = UserService.new(self).following
    formatted_following = following.map do |follow|
      Following.new(follow)
    end
  end

  def followers
    followers = UserService.new(self).followers
    formatted_followers = followers.map do |follow|
      Follower.new(follow)
    end
  end

  def repos
    repos = UserService.new(self).repos
    formatted_repos = repos.map do |repo|
      Repository.new(repo)
    end
    formatted_repos
  end

  def organizations
    organizations = UserService.new(self).organizations
    formatted_orgs = organizations.map do |organization|
      Organization.new(organization)
    end
    formatted_orgs
  end

  def commits
    formatted_commits = []
    repos = UserService.new(self).repos
    repos_commits = repos.map do |repo|
      UserService.new(self).repo_commits(repo)
    end
    repos_commits.map do |commits|
      commits.find_all do |commit|
        commit["author"]["id"] == self.uid.to_i
      end.each do |commit|
        formatted_commits << Commit.new(commit)
      end
    end
    sorted_commits = formatted_commits.sort_by do |commit|
      commit.created_at
    end.reverse
    sorted_commits[0...10]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end





# def create
#   if request.env["omniauth.auth"]
#     connection = Faraday.new("https://api.github.com")
#     connection.headers["Authorization"] = "token " + request.env["omniauth.auth"].credentials.token
#     @repositories = JSON.parse(connection.get("/user/repos").body)
#     render :index
#   else
#     redirect_to root_path
#   end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
<h1> Welcome to API Curious </h1>
<% if current_user %>
  Hello, <%= current_user.nickname %>
  <br>
  <%= link_to "View Your Dashboard", dashboard_path %>
  <br><br>
  <%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Github Login", github_login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %> </h1>

<%= image_tag @user.avatar_url, size: "300x300", alt: "Profile Image" %>
<br>
<p>Followers: <%= @user.followers.count %></p>
<p>Following: <%= @user.following.count %></p>
<p>Starred Repos:  <%= @user.stars.count %> </p>
<p>Recent Commits: <ul> <% @user.commits.each do |commit| %>
  <li> <%= commit.repo %>, <%= commit.message %> -- <%= commit.author %>, <%= commit.created_at %> </li>
<% end %>
</ul></p>
<p>Organizations: <ul> <% @user.organizations.each do |org| %>
  <li> <%= org.name %>, <%= org.url %> </li>
<% end %>
</ul></p>
<p>Repositories: <ul> <% @user.repos.each do |repo| %>
  <li> <%= repo.name %>, owned by: <%= repo.owner %> -- <%= repo.url %> </li>
<% end %>
</ul></p>